background = 0xFFF7F7F7
base = 0xFFEBEBEB
text = 0xFF181818
alternate_base = 0xFFF2F2F2
bright_text = 0xFF181818
accent = 0xFF181818
link_text = 0xFF181818
accent_secondary = 0xFF454545
font_family = "Terminus (TTF)"
font_family_monospace = "monospace"
font_size = 11
small_font_size = 10
rounding_large = 8
rounding_small = 4
